### ISSUE TITLE
Web App - Unavailable (403)

### ISSUE THREAD

**Issue by samwalshnz** [zumwald/stateless-vsts-oauth#1]
![screen shot 2018-09-17 at 11 52 30 am](https://user-images.githubusercontent.com/1085227/45602311-326e6800-ba70-11e8-82c7-68d9ff4bea40.png)

Is the site down - exceeded Azure usage limit?

**Comment by zumwald** [comment]
Apologies for the late responseand the downtime. The site indeed went down for a few days due to the spending limit being hit in the subscription where I host it.

I've removed the limit and will keep amore watchful eye out. Worst case if it happened again it would just cost me a few dollars rather than messing with your flow. Apologies again for the inconvenience!

**Comment by lucasjaviluna** [comment]
Hi zumwald, this issue is happening again
